version: '3'
services:
  php:
    image: php:latest
    volumes:
      - ./php:/var/www/html
    ports:
      - 8080:80
    env_file:
      - .env

  mysql:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
  
  vue:
    build:
      context: ./your-vue-app
      dockerfile: Dockerfile
    ports:
      - 8081:80