version: '3'
services:
  api:
    image: peopsquik/php:latest
    volumes:
      - ./api:/var/www/html
    ports:
      - 8084:80
    env_file:
      - .env
    depends_on:
      - mysql
    command: php -S 0.0.0.0:80 -t /var/www/html/public
  
  mysql:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  
  vue:
    image: node:latest
    ports:
      - 5173:5173
    volumes:
      - ./:/app
    command: sh -c "cd /app && echo $PWD && npm install && npm run dev"
